/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as McpStorageProvisionRouteImport } from './routes/mcp.storage.provision'
import { Route as McpServiceStatusRouteImport } from './routes/mcp.service.status'
import { Route as McpPaymentAttachRouteImport } from './routes/mcp.payment.attach'
import { Route as McpKeysRotateRouteImport } from './routes/mcp.keys.rotate'
import { Route as McpAccountCreateRouteImport } from './routes/mcp.account.create'

const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const McpStorageProvisionRoute = McpStorageProvisionRouteImport.update({
  id: '/storage/provision',
  path: '/storage/provision',
  getParentRoute: () => McpRoute,
} as any)
const McpServiceStatusRoute = McpServiceStatusRouteImport.update({
  id: '/service/status',
  path: '/service/status',
  getParentRoute: () => McpRoute,
} as any)
const McpPaymentAttachRoute = McpPaymentAttachRouteImport.update({
  id: '/payment/attach',
  path: '/payment/attach',
  getParentRoute: () => McpRoute,
} as any)
const McpKeysRotateRoute = McpKeysRotateRouteImport.update({
  id: '/keys/rotate',
  path: '/keys/rotate',
  getParentRoute: () => McpRoute,
} as any)
const McpAccountCreateRoute = McpAccountCreateRouteImport.update({
  id: '/account/create',
  path: '/account/create',
  getParentRoute: () => McpRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/mcp': typeof McpRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/storage': typeof StorageRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/mcp/account/create': typeof McpAccountCreateRoute
  '/mcp/keys/rotate': typeof McpKeysRotateRoute
  '/mcp/payment/attach': typeof McpPaymentAttachRoute
  '/mcp/service/status': typeof McpServiceStatusRoute
  '/mcp/storage/provision': typeof McpStorageProvisionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/mcp': typeof McpRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/storage': typeof StorageRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/mcp/account/create': typeof McpAccountCreateRoute
  '/mcp/keys/rotate': typeof McpKeysRotateRoute
  '/mcp/payment/attach': typeof McpPaymentAttachRoute
  '/mcp/service/status': typeof McpServiceStatusRoute
  '/mcp/storage/provision': typeof McpStorageProvisionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/mcp': typeof McpRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/storage': typeof StorageRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/mcp/account/create': typeof McpAccountCreateRoute
  '/mcp/keys/rotate': typeof McpKeysRotateRoute
  '/mcp/payment/attach': typeof McpPaymentAttachRoute
  '/mcp/service/status': typeof McpServiceStatusRoute
  '/mcp/storage/provision': typeof McpStorageProvisionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/demo'
    | '/mcp'
    | '/payments'
    | '/rss.xml'
    | '/storage'
    | '/blog/$slug'
    | '/blog/'
    | '/mcp/account/create'
    | '/mcp/keys/rotate'
    | '/mcp/payment/attach'
    | '/mcp/service/status'
    | '/mcp/storage/provision'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/demo'
    | '/mcp'
    | '/payments'
    | '/rss.xml'
    | '/storage'
    | '/blog/$slug'
    | '/blog'
    | '/mcp/account/create'
    | '/mcp/keys/rotate'
    | '/mcp/payment/attach'
    | '/mcp/service/status'
    | '/mcp/storage/provision'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/demo'
    | '/mcp'
    | '/payments'
    | '/rss.xml'
    | '/storage'
    | '/blog/$slug'
    | '/blog/'
    | '/mcp/account/create'
    | '/mcp/keys/rotate'
    | '/mcp/payment/attach'
    | '/mcp/service/status'
    | '/mcp/storage/provision'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  McpRoute: typeof McpRouteWithChildren
  PaymentsRoute: typeof PaymentsRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  StorageRoute: typeof StorageRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/storage/provision': {
      id: '/mcp/storage/provision'
      path: '/storage/provision'
      fullPath: '/mcp/storage/provision'
      preLoaderRoute: typeof McpStorageProvisionRouteImport
      parentRoute: typeof McpRoute
    }
    '/mcp/service/status': {
      id: '/mcp/service/status'
      path: '/service/status'
      fullPath: '/mcp/service/status'
      preLoaderRoute: typeof McpServiceStatusRouteImport
      parentRoute: typeof McpRoute
    }
    '/mcp/payment/attach': {
      id: '/mcp/payment/attach'
      path: '/payment/attach'
      fullPath: '/mcp/payment/attach'
      preLoaderRoute: typeof McpPaymentAttachRouteImport
      parentRoute: typeof McpRoute
    }
    '/mcp/keys/rotate': {
      id: '/mcp/keys/rotate'
      path: '/keys/rotate'
      fullPath: '/mcp/keys/rotate'
      preLoaderRoute: typeof McpKeysRotateRouteImport
      parentRoute: typeof McpRoute
    }
    '/mcp/account/create': {
      id: '/mcp/account/create'
      path: '/account/create'
      fullPath: '/mcp/account/create'
      preLoaderRoute: typeof McpAccountCreateRouteImport
      parentRoute: typeof McpRoute
    }
  }
}

interface McpRouteChildren {
  McpAccountCreateRoute: typeof McpAccountCreateRoute
  McpKeysRotateRoute: typeof McpKeysRotateRoute
  McpPaymentAttachRoute: typeof McpPaymentAttachRoute
  McpServiceStatusRoute: typeof McpServiceStatusRoute
  McpStorageProvisionRoute: typeof McpStorageProvisionRoute
}

const McpRouteChildren: McpRouteChildren = {
  McpAccountCreateRoute: McpAccountCreateRoute,
  McpKeysRotateRoute: McpKeysRotateRoute,
  McpPaymentAttachRoute: McpPaymentAttachRoute,
  McpServiceStatusRoute: McpServiceStatusRoute,
  McpStorageProvisionRoute: McpStorageProvisionRoute,
}

const McpRouteWithChildren = McpRoute._addFileChildren(McpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  McpRoute: McpRouteWithChildren,
  PaymentsRoute: PaymentsRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  StorageRoute: StorageRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
